# -*- coding: utf-8 -*-
"""Assignment 2 Internship.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PwGg9ZUTwqmPLjEuTLn0p5i3kFDWm-c-
"""

username = input("Enter username: ")
password = input("Enter password: ")

if username == "admin" and password == "1234":
    print("Login successful")
else:
    print("Access denied")

num = int(input("Enter a number: "))

for i in range(1, 11):
    print(num, "x", i, "=", num * i)

user_input = ""

while user_input != "exit":
    user_input = input("Enter something (type 'exit' to stop): ")

num = int(input("Enter a number: "))

if num > 1:
    is_prime = True
    for i in range(2, num):
        if num % i == 0:
            is_prime = False
            break

    if is_prime:
        print("Prime number")
    else:
        print("Not a prime number")
else:
    print("Not a prime number")

text = input("Enter a string: ")

for char in text:
    if char.isupper():
        print(char)