# -*- coding: utf-8 -*-
"""Assignment 3rd Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XC8cHVuLtSPNWLYlLUiIm2OqG4A80rDV
"""

numbers = [10, 20, 5, 40, 30]

largest = second = float('-inf')

for num in numbers:
    if num > largest:
        second = largest
        largest = num
    elif num > second and num != largest:
        second = num

print("Second largest:", second)

text = input("Enter a string: ")
i = len(text) - 1

while i >= 0:
    print(text[i], end="")
    i -= 1

numbers = [1, 2, 3, 4, 5, 6]

count = 0
for num in numbers:
    if num % 2 == 0:
        count += 1

print("Even numbers:", count)

data = {"a": 30, "b": 60, "c": 80}

for key, value in data.items():
    if value > 50:
        print(key)

numbers = {5, 12, 8, 20, 15}

for num in numbers:
    if num > 10:
        print(num)