# -*- coding: utf-8 -*-
"""Assignment 1 Int.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TUJxYbb_AqWsh5iiiMhtMGL2JoIFwufX
"""

for i in range(1, 21):
    if i % 2 == 0:
        print(i)

num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even Number")
else:
    print("Odd Number")

a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Remainder:", a % b)
print("Floor Division:", a // b)

emp_id = 101
salary = 50000.50
department = "Finance"

print(type(emp_id))
print(type(salary))
print(type(department))

company = "Awesome Chocolates"
employee = "Anuj Kumar"
salary = 50000

print(f"{employee} works at {company} and earns ₹{salary}")